apiVersion: v1
kind: Service
metadata:
  name: django-todo-cicd-service
spec:
  type: NodePort
  selector:
    app: django-todo-cicd-project
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
